version: '3.1'
services:
  cassandra1:
    image: cassandra:latest
    container_name: NodeCassandra1
    hostname: cassandra1
    ports:
      - "9042:9042"
    expose:
        - 7000 # внутренней порт (обмен информацией о состоянии кластера с другими узлами)/протокол Gossip
        - 7001 # внутренний порт/протокол Gossip через TLS (защищенный)
        - 7199 # порт для подключения к сервису JMX (мониторинг и управление экземплярами cassandra)
        - 9042 # порт для внешнего доступа извне через CQL
        - 9142 # порт для протокола CQL SSL
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - NUM_TOKENS=3 # количество токенов, которые будет иметь данный узел/ токен -это числовое значение, которое используется для разделения и распределения данных по узлам кластера.
      # Если все узлы кластера запускаются на одной машине с использованием docker-compose, то достаточно установить одно и то же имя DC
      # Имя центра данных (data center), к которому принадлежит данный узел/для правильной настройки репликации данных и обеспечения согласованности и доступности данных в кластере
      - DC=DC1
      - DS_LICENSE=accept # Подтверждение лицензионного соглашения DataStax
      - RACK=RAC1 # имя стойки (rack), в которой находится данный узел/ Стойка - это логическая группировка узлов в кластере Cassandra
      # --- параметры настройки памяти для Java Virtual Machine (JVM), на которой работает Cassandra
      - MAX_HEAP_SIZE=1G # размер максимальной heap size/ область памяти, используемая для хранения объектов и выполнения операций в Java
      # Новое поколение - это часть кучи, где создаются и сначала размещаются объекты в Java-приложении.
      # Затем, при необходимости, объекты могут быть перемещены в другую часть кучи, называемую старым поколением
      - HEAP_NEWSIZE=200M # указывает размер new generation heap
      # ---
      - START_RPC=false  # Отключение RPC-сервиса Cassandra/ удаленный доступ между узлами кластера и клиентскими приложениями
    networks:
      cassandra_net:
        ipv4_address: 192.168.0.2
    ulimits:
      memlock: -1
      nproc: 32768 # max количество процессов в контейнере
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.5'

  cassandra2:
    image: cassandra:latest
    container_name: NodeCassandra2
    hostname: cassandra2
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - NUM_TOKENS=3
      - DC=DC2
      - DS_LICENSE=accept
      - RACK=RAC1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - START_RPC=false
    ports:
      - "9043:9042"
    expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9142
    networks:
      cassandra_net:
        ipv4_address: 192.168.0.3
    depends_on:
       - cassandra1
    ulimits:
      memlock: -1
      nproc: 32768
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.5'

  cassandra3:
    image: cassandra:latest
    container_name: NodeCassandra3
    hostname: cassandra3
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - NUM_TOKENS=3
      - DC=DC2
      - DS_LICENSE=accept
      - RACK=RAC1
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
      - START_RPC=false
    ports:
      - "9044:9042"
    expose:
        - 7000
        - 7001
        - 7199
        - 9042
        - 9142
    networks:
      cassandra_net:
        ipv4_address: 192.168.0.4
    depends_on:
       - cassandra1
       - cassandra2
    ulimits:
      memlock: -1
      nproc: 32768
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '0.5'
networks:
  cassandra_net:
    driver: macvlan
    driver_opts:
      parent: wlp0s20f3
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1

